services:
  postgres:
    image: postgres:16
    container_name: notes_postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: notes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
