export const REFRESH_TOKEN_KEY = 'notes-rt';
export const ACCESS_TOKEN_EXPIRATION = '5m';
export const REFRESH_TOKEN_EXPIRATION_IN_DAYS = 30;
export const REFRESH_TOKEN_EXPIRATION = REFRESH_TOKEN_EXPIRATION_IN_DAYS + 'd';
